### ISSUE TITLE
Uploaded Lesson Image is not visible after editing the lesson 

### ISSUE THREAD

**Issue by Ravichandratech** [ISTARSkills/viksit-cms#19]
1. Edit a lesson and upload the image from content creator.
2. Login as content admin and edit the same lesson 
3.In image field uploaded image is not visible.
![image](https://user-images.githubusercontent.com/28383663/39120929-ad0c88e8-470d-11e8-9f8c-e1d2321e2345.png)

**Comment by vinayistar** [comment]
Cache problem
