### ISSUE TITLE
Content Admin Course list view (Course Tab)

### ISSUE THREAD

**Issue by vinayistar** [ISTARSkills/viksit-cms#3]
![image](https://user-images.githubusercontent.com/16954148/35395284-f3717e08-020f-11e8-99af-ce2efeaa2757.png)

**Comment by verma6uc** [comment]
➤ Vinay Sharma commented:

Filtering/Structure Done...Need to discuss about publish Course and lesson.

**Comment by verma6uc** [comment]
➤ Vaibhav Verma commented:

Please talk to sreeram about it from the tech point of view it should be done
