### ISSUE TITLE
Content Admin Dashboard UI

### ISSUE THREAD

**Issue by vinayistar** [ISTARSkills/viksit-cms#6]
![image](https://user-images.githubusercontent.com/16954148/35395673-0487a810-0211-11e8-81c7-6419a392997e.png)

![image](https://user-images.githubusercontent.com/16954148/35396017-dd0bd0d0-0211-11e8-91ec-f3c22626a62b.png)

Left Graph shows overall course completion with there status

Right Graph shows an individual person progress status.

**Comment by Sumanth-istar** [comment]
only graph part is pending
